### ISSUE TITLE
Shortcode does not have privacy and shows the To-Dos of all users

### ISSUE THREAD

**Issue by collex100** [wbcomdesigns/buddypress-user-todo-list#17]
Shortcode does not have privacy and shows the To-Dos of all users
Wordpress 4.9.4

![screenshot_1](https://user-images.githubusercontent.com/11208423/37362321-ec955526-2705-11e8-9783-68387b5efb52.jpg)

![screenshot_2](https://user-images.githubusercontent.com/11208423/37362588-b21c27ac-2706-11e8-8bb3-e4380eb4649c.jpg)

**Comment by wbcomdev** [comment]
Thanx collex100, I have checked the issue will try to fix it in next update.

**Comment by collex100** [comment]
ok, it is work
