### ISSUE TITLE
Not correctly displaying the shotscode in the widget.

### ISSUE THREAD

**Issue by collex100** [wbcomdesigns/buddypress-user-todo-list#18]
Not correctly displaying the shotscode in the widget.
To DO are always above the name of the widget.
![screenshot_1](https://user-images.githubusercontent.com/11208423/37239354-2b4090a0-244b-11e8-9230-bb5185ecac4e.jpg)

**Comment by wbcomdev** [comment]
We have not provided widgets support in current plugin version.

**Comment by collex100** [comment]
ok, thanks.
