### ISSUE TITLE
No instructions to the plugin, how to align the layers

### ISSUE THREAD

**Issue by collex100** [wbcomdesigns/buddypress-user-todo-list#20]
The width of the task board shifts the widget's area down.

![screenshot_6](https://user-images.githubusercontent.com/11208423/37239511-6f094d1a-244e-11e8-9310-9b80eb70c6e9.jpg)

**Comment by wbcomdev** [comment]
In current plugin version we do not provide support for widget's css, as we do not provide widget in the plugin's current version. You can solve the issue with custom css.

**Comment by collex100** [comment]
ok, thanks!
